# COLOURS
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)

# SIZE
MAIN_WIDTH = 500
MAIN_HEIGHT = 400

CIRCLE_RADIUS = 5

AXE_WIDTH = 2


# BORDERS
MAIN_BORDER = 20

BOTTOM_LEFT_BORDER = (MAIN_BORDER, MAIN_HEIGHT - MAIN_BORDER)
BOTTOM_RIGHT_BORDER = (MAIN_WIDTH - MAIN_BORDER, MAIN_HEIGHT - MAIN_BORDER)
TOP_LEFT_BORDER = (MAIN_BORDER, MAIN_BORDER)

# WRITINGS
FONT_SIZE = 9

X_AXE_WRITE = 'Dim. casa (m^2)'
Y_AXE_WRITE = 'Prezzo casa (migliaia €)'

X_AXE_WRITE_POSITION = (450, 360)
Y_AXE_WRITE_POSITION = (60, 10)

# GRADIENT DESCENT OF COST FUNCTION (LINEAR REGRESSION)
ALPHA = 0.0001
CONVERGENCY = 0.001
CONVERGENCY_SI = 0.01
CONVERGENCY_TO = 0.001
THETA_0 = 0
THETA_1 = 0
